
CREATE TABLE IF NOT EXISTS SWF_USER(
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
SN VARCHAR(40) NOT NULL,
RANK TINYINT(1) NOT NULL
);


CREATE TABLE IF NOT EXISTS WEATHER_COND(
ID SMALLINT(2) AUTO_INCREMENT PRIMARY KEY,
NAME VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS RECORD(
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
TEMPERATURE SMALLINT(3) NOT NULL,
LATITUDE FLOAT,
LONGITUDE FLOAT,
SUN_COND SMALLINT(2),
RAIN_COND SMALLINT(2),
USER_ID INT NOT NULL,
TIME_STAMP TIMESTAMP NOT NULL,
CITY VARCHAR(40) NOT NULL, 
COUNTRY VARCHAR(40) NOT NULL,
FOREIGN KEY(SUN_COND) REFERENCES WEATHER_COND(ID),
FOREIGN KEY(RAIN_COND) REFERENCES WEATHER_COND(ID),
FOREIGN KEY(USER_ID) REFERENCES SWF_USER(ID)
);
